# Generated by Django 5.0.2 on 2024-09-13 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='image_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
